server.port=80

#Para definir el formato de despliegue de fecha/hora del log en la consola

logging.pattern.dateformat=hh:mm

#Para eliminar mensajes invasivos de Spring

spring.main.banner-mode=off

#Para que en tiempo de desarrollo se deje de usar el "cache" del servidor .. en producción si...

spring.thymeleaf.cache=false